const SUBMIT_REVIEW = 'SUBMIT_REVIEW';
const SUBMITTING_REVIEW = 'SUBMITTING_REVIEW';
const SUBMIT_RATING = 'SUBMIT_RATING';
const SUBMITTING_RATING = 'SUBMITTING_RATING';
const DELETE_TRIP = 'DELETE_TRIP';
const OPEN_REVIEW = 'OPEN_REVIEW';
const OPEN_RATING = 'OPEN_RATING';
const CLOSE_FORM = 'CLOSE_FORM';


export default {
  SUBMIT_REVIEW,
  SUBMITTING_REVIEW,
  SUBMIT_RATING,
  SUBMITTING_RATING,
  DELETE_TRIP,
  OPEN_REVIEW,
  OPEN_RATING,
  CLOSE_FORM
}