const SUBMIT_REVIEW = 'SUBMIT_REVIEW';
const DELETE_TRIP = 'DELETE_TRIP';
const OPEN_REVIEW = 'OPEN_REVIEW';
const CLOSE_REVIEW = 'CLOSE_REVIEW';
const SUBMITTING = 'SUBMITTING';


export default {
  SUBMIT_REVIEW,
  DELETE_TRIP,
  OPEN_REVIEW,
  CLOSE_REVIEW,
  SUBMITTING
}