const SUBMIT_REVIEW = 'SUBMIT_REVIEW';
const DELETE_TRIP = 'DELETE_TRIP';
const TRIP_OPEN = 'TRIP_OPEN';
const TRIP_CLOSE = 'TRIP_CLOSE';


export default {
  SUBMIT_REVIEW,
  DELETE_TRIP,
  TRIP_OPEN, 
  TRIP_CLOSE
}