const ADD_TRIPS = 'ADD_TRIPS';
const ADD_CLICKED = 'ADD_CLICKED';
const ADD_DATE = 'ADD_DATE';
const ADD_START = 'ADD_START';
const ADD_END = 'ADD_END';
const FILTER_DRIVERS = 'FILTER_DRIVERS';
const RESET_SEARCH = 'RESET_SEARCH';

export default {
  ADD_TRIPS,
  ADD_CLICKED,
  ADD_DATE,
  ADD_START,
  ADD_END,
  FILTER_DRIVERS,
  RESET_SEARCH
}