const CLICK_SEARCH = 'CLICK_SEARCH';
const DATE_CLICKED = 'DATE_CLICKED';
const START_CLICKED = 'START_CLICKED';
const END_CLICKED = 'END_CLICKED';
const ADD_DATE = 'ADD_DATE';
const ADD_START = 'ADD_START';
const ADD_END = 'ADD_END';
const RESET_SEARCH = 'RESET_SEARCH';
const SORT_DRIVERS = 'SORT_DRIVERS'

export default {
  CLICK_SEARCH,
  DATE_CLICKED,
  START_CLICKED,
  END_CLICKED,
  ADD_DATE,
  ADD_START,
  ADD_END,
  RESET_SEARCH,
  SORT_DRIVERS
}