const ADD_SEARCH = 'ADD_SEARCH';
const DATE_CLICKED = 'DATE_CLICKED';
const ADD_DATE = 'ADD_DATE';
const ADD_START = 'ADD_START';
const ADD_END = 'ADD_END';
const RESET_SEARCH = 'RESET_SEARCH';

export default {
  ADD_SEARCH,
  DATE_CLICKED,
  ADD_DATE,
  ADD_START,
  ADD_END,
  RESET_SEARCH
}