const ADD_DRIVER = 'ADD_DRIVER';
const BOOK_RIDE = 'BOOK_RIDE';
const RESET_BOOKED = 'RESET_BOOKED';
const SET_TIME = 'SET_TIME';
const SELECT_DAY = 'SELECT_DAY';
const LOADING_DRIVER = 'LOADING_DRIVER';


export default {
  ADD_DRIVER,
  BOOK_RIDE,
  RESET_BOOKED,
  SET_TIME,
  SELECT_DAY,
  LOADING_DRIVER
}