const ADD_DRIVER_TRIPS = 'ADD_DRIVER_TRIPS';
const BOOK_RIDE = 'BOOK_RIDE';
const RESET_BOOKED = 'RESET_BOOKED';
const SET_TIME = 'SET_TIME';
const SELECT_DAY = 'SELECT_DAY'


export default {
  ADD_DRIVER_TRIPS,
  BOOK_RIDE,
  RESET_BOOKED,
  SET_TIME,
  SELECT_DAY
}